export let  QUANTITY_INCREASES = 'QUANTITY_INCREASES';
export let QUANTITY_DECREASED = 'QUANTITY_DECREASED';
export let SORT_HEIGH_TO_LOW = 'SORT_HEIGH_TO_LOW';
export let SORT_LOW_TO_HEIGHT = 'SORT_LOW_TO_HEIGHT';
export let SORT_BY_DISCOUNT = 'SORT_BY_DISCOUNT';
export let FILTER_ELEMENT = 'FILTER_ELEMENT';
export let SEARCH_ELEMENT = 'SEARCH_ELEMENT';
